// Auto-generated by news_pipeline_web
// Generated: 2026-01-29T16:56:18.330535+00:00
// Articles: 7

const articles = [
    {
        "id": 1,
        "title": "Quote of the day by Premanand Ji Maharaj: \"Protect Celibacy. Celibacy Is a Great Nectar Element; Due to Foolishness, People Don’t Pay Attention to It\"",
        "summary": "Hindu Mythology News: Premanand ji Maharaj is the most famous spiritual teacher, who is an ardent devotee of Goddess Radha and Lord Krishna. He guides countless people with.",
        "category": "Times of India • IN",
        "image": "https://static.toiimg.com/thumb/msid-127754674,width-1280,height-720,imgsize-27776,resizemode-6,overlay-toi_sw,pt-32,y_pad-600/photo.jpg",
        "trafficLightStatus": "green",
        "misleadingScore": 0,
        "content": "<p>Premanand ji Maharaj is the most famous spiritual teacher, who is an ardent devotee</p>\n<p>of Goddess Radha and Lord Krishna. He guides countless people with his devotion and</p>\n<p>love. \"Protect Celibacy. Celibacy Is a Great Nectar Element; Due to Foolishness, P... [2358</p>\n<p>chars]</p>",
        "url": "https://timesofindia.indiatimes.com/religion/hindu-mythology/quote-of-the-day-by-premanand-ji-maharaj-protect-celibacy-celibacy-is-a-great-nectar-element-due-to-foolishness-people-dont-pay-attention-to-it/articleshow/127753546.cms",
        "publishedAt": "2026-01-29T04:52:00Z"
    },
    {
        "id": 2,
        "title": "She Accepted A Lift. Minutes Later, She Was Raped In A Moving Car",
        "summary": "Two men were arrested after a 25-year-old woman was allegedly assaulted inside a moving car in Rudrapur’s Transit Camp area, police said., Crime News, Times Now",
        "category": "Times Now • IN",
        "image": "https://images.timesnownews.com/thumb/msid-153523942,width-1280,height-720,resizemode-75/153523942.jpg",
        "trafficLightStatus": "green",
        "misleadingScore": 15,
        "content": "<p>A 25-year-old woman was raped inside a moving car by two men in Rudrapur's Transit Camp</p>\n<p>area. According to the police, the survivor said she was walking from her home to her</p>\n<p>workplace in Pantnagar on the morning of January 25 when two men offered her... [1245 chars]</p>",
        "url": "https://www.timesnownews.com/crime/uttarakhand-rudrapur-woman-raped-in-moving-car-two-arrested-article-153523942",
        "publishedAt": "2026-01-29T04:53:39Z"
    },
    {
        "id": 3,
        "title": "Parul Gulati on starring in ‘Tu Yaa Main’: Anand L Rai’s world is theatrical, layered, emotionally rich",
        "summary": "Parul Gulati on starring in ‘Tu Yaa Main’: Anand L Rai’s world is theatrical, layered, emotionally rich - Mumbai, Jan 29 Actress Parul Gulati, who will be seen in the upcoming thriller “Tu Yaa Main” starring ... Get Latest News on Entertainment only on lokmattimes.com",
        "category": "Lokmat Times • IN",
        "image": "https://d3pc1xvrcw35tl.cloudfront.net/ln/feedImages/1200x900/202601293654680_202601.jpeg",
        "trafficLightStatus": "green",
        "misleadingScore": 0,
        "content": "<p>Mumbai, Jan 29 Actress Parul Gulati, who will be seen in the upcoming thriller</p>\n<p>“Tu Yaa Main” starring Adarsh Gourav and Shanaya Kapoor, has spoken about filmmaker Anand</p>\n<p>L Rai and said that his “world is theatrical, layered and emotionally rich.” Paru...</p>\n<p>[3112 chars]</p>",
        "url": "https://www.lokmattimes.com/entertainment/parul-gulati-on-starring-in-tu-yaa-main-anand-l-rais-world-is-theatrical-layered-emotionally-rich/",
        "publishedAt": "2026-01-29T04:54:19Z"
    },
    {
        "id": 4,
        "title": "Rahul seeks early start to talks on TN seat sharing as Kanimozhi calls on him",
        "summary": "India News: NEW DELHI: DMK parliamentary party head K Kanimozhi met Congress leader Rahul Gandhi at his residence for a discussion Wednesday, where Congress urged.",
        "category": "Times of India • IN",
        "image": "https://static.toiimg.com/thumb/msid-127756091,width-1280,height-720,imgsize-47492,resizemode-6,overlay-toi_sw,pt-32,y_pad-600/photo.jpg",
        "trafficLightStatus": "yellow",
        "misleadingScore": 45,
        "content": "<p>NEW DELHI: DMK parliamentary party head K Kanimozhi met Congress leader Rahul Gandhi</p>\n<p>at his residence for a discussion Wednesday, where Congress urged the southern partner</p>\n<p>to start the already delayed discussions on seat-sharing for the coming Tamil ...</p>\n<p>[2143 chars]</p>",
        "url": "https://timesofindia.indiatimes.com/india/rahul-seeks-early-start-to-talks-on-tn-seat-sharing-as-kanimozhi-calls-on-him/articleshow/127756164.cms",
        "publishedAt": "2026-01-29T04:55:00Z"
    },
    {
        "id": 5,
        "title": "SBI SCO registration window opens for 2050 posts: Direct link to apply here",
        "summary": "News News: SBI SCO application 2026: The State Bank of India (SBI) has opened online applications for Circle Based Officer (CBO) posts. Interested and eligible c.",
        "category": "Times of India • IN",
        "image": "https://static.toiimg.com/thumb/msid-127756040,width-1280,height-720,imgsize-279031,resizemode-6,overlay-toi_sw,pt-32,y_pad-600/photo.jpg",
        "trafficLightStatus": "red",
        "misleadingScore": 67,
        "content": "<p>SBI SCO registration SBI SCO application 2026: The State Bank of India (SBI)</p>\n<p>has opened online applications for Circle Based Officer (CBO) posts. Interested and eligible</p>\n<p>candidates can apply through SBI’s official website, sbi.co.in. The recruitment ... [2755 chars]</p>",
        "url": "https://timesofindia.indiatimes.com/education/news/sbi-sco-registration-window-opens-for-2050-posts-direct-link-to-apply-here/articleshow/127756001.cms",
        "publishedAt": "2026-01-29T04:54:00Z"
    },
    {
        "id": 6,
        "title": "How India prepares the Union Budget: Inside the official process ahead of 2026 reveal",
        "summary": "Finance Minister Nirmala Sitharaman will present the Union Budget for 2026-27 on February 1, her ninth consecutive budget.| India News",
        "category": "Hindustan Times • IN",
        "image": "https://www.hindustantimes.com/ht-img/img/2026/01/29/550x309/ANI-20260108250-0_1769661818976_1769661836904.jpg",
        "trafficLightStatus": "red",
        "misleadingScore": 67,
        "content": "<p>India's finance minister Nirmala Sitharaman will to present the Union Budget for 2026-27 in</p>\n<p>Parliament on February 1, marking her ninth consecutive budget, at a time when India’s</p>\n<p>economy is expected to grow at 7.6 per cent in the current financial ye...</p>\n<p>[4079 chars]</p>",
        "url": "https://www.hindustantimes.com/india-news/how-india-prepares-the-union-budget-inside-the-official-process-ahead-of-2026-reveal-101769512153346.html",
        "publishedAt": "2026-01-29T04:54:38Z"
    },
    {
        "id": 7,
        "title": "Ray J Reveals He Has A Year To Live Due To \"Black\" Heart",
        "summary": "Ray J has recently opened up about his unfortunate health news, following a recent hospitalization.",
        "category": "Deadline • US",
        "image": "https://deadline.com/wp-content/uploads/2026/01/P102EFY-e1769661321198.jpg?w=893",
        "trafficLightStatus": "red",
        "misleadingScore": 67,
        "content": "<p>Ray J has recently opened up about his unfortunate health news, following a recent</p>\n<p>hospitalization. The musician and actor revealed that he doesn’t expect to live beyond 2027</p>\n<p>after drug and alcohol use has damaged his heart, and left it “only beating...</p>\n<p>[1235 chars]</p>",
        "url": "https://deadline.com/2026/01/ray-j-year-to-live-black-heart-alcohol-drug-use-1236700880/",
        "publishedAt": "2026-01-29T04:52:52Z"
    }
];
